platform :ios, '10.0'

target 'GVRSDK-Wrapper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GVRSDK-Wrapper
  pod 'GTMSessionFetcher/Core'
  pod 'GoogleToolboxForMac/Logger'
end
